.TH edgo 3 "2026-08-03"
.SH NAME
edgo \- text editor library with native lsp support
.SH SYNOPSIS
.B #include <edgo.h>
.SH MODULE OVERVIEW
.SS Screen printing functions
Functions that are manipulating the text buffer while printing the screen content.
.TP
struct screen \f3add_text\fP(const char *\fIbuf\fP, size_t \fIlength\fP);
Adds character or text to the buffer.
.TP
struct screen \f3replace_text\fP(size_t \fIps\fP, size_t \fIpe\fP, const char *\fIbuf\fP, size_t \fIlength\fP);
Replaces text between ranges of character positions.
.TP
struct screen \f3move_cursor\fP(size_t \fIline\fP, size_t \fIpos\fP);
Moves cursor to position.
.TP
struct screen \f3display_screen_report\fP(const char *\fIdirpath\fP, size_t \fIlength\fP);
Displaying screen report of the current working folder.
.TP
struct screen \f3clipboard\fP(enum clipboard_ops \fIops\fP);
Clipboard operations are handled according the parameter.
.TP
struct screen \f3duplicate\fP(void);
Duplicates the currently selected line under cursor.
.TP
struct screen \f3commentline\fP(void);
Adds comment character(s) to the beginning of the line.
.TP
struct screen \f3swaplinesup\fP(void);
Moves current line up under the cursor.
.TP
struct screen \f3swaplinesdn\fP(void);
Moves current line down under the cursor.
.SS Navigation keys
Navigation handler functions are also printing screen content.
.TP
struct screen \f3on_keypress\fP(enum nav_keys \fIkeys\fP, bool \fIis_paging\fP, bool \fIis_shift\fP);
Handles key presses according to the parameter.
.TP
struct screen \f3on_scroll\fP(enum nav_keys \fIkeys\fP);
This is only for UP and DOWN scrolling for mouse inputs.
.SS File operations
File operations have to be invoked at the start for initializing the library.
.TP
struct screen \f3open_file\fP(const char *\fIfilepath\fP);
Opens file providing the file path in the argument.
.TP
int \f3new_file\fP(const char *\fIfilename\fP);
Creates a new file in the current working directory by providing the name only.
.TP
int \f3save_file\fP(void);
Saves the file currently being opened.
.SS LSP client functions
Commands initiated by the user for interaction with the language server.
.TP
void \f3lsp_client_hover\fP(struct lsp_hover*);
Displays information when hovering the cursor under a text.
.TP
void \f3lsp_client_completion\fP(struct lsp_completion*);
Provides auto-complete suggestions.
.TP
void \f3lsp_client_definition\fP(struct lsp_definition*);
Jumps to the definition or declaration under the cursor.
.TP
void \f3lsp_client_signature_help\fP(struct lsp_signature_help*);
Displays signature information of the current method.
.TP
void \f3lsp_client_references\fP(struct lsp_references*);
Retrieves the list of references in the working directory.
.TP
void \f3lsp_client_prepare_rename\fP(struct lsp_prepare_rename*);
Determines if a symbol can be renamed safely before it is being renamed.
.TP
void \f3lsp_client_rename\fP(const char* \fInewname\fP, struct lsp_rename*);
Renames a symbol under cursor.
.TP
void \f3lsp_client_code_action\fP(struct lsp_code_action*);
Returns a list of possible actions for the file being opened.
.SS LSP diagnostics
This function can be called whenever the user needs diagnostics.
.TP
void \f3lsp_diagnostics\fP(struct lsp_publish_diagnostics*);
Retrieves diagnostics from the currently opened file.
.SH PARAMETERS
.TP
\f2ops\fP
Specifies the clipboard buffer operation.
Symbolic constants
\%\f3COPY\fP,
\%\f3PASTE\fP,
\%\f3CUT\fP,
\%\f3UNDO\fP,
and
\%\f3REDO\fP are accepted.
.TP
\f2keys\fP
Specifies the navigation keys pressed such as
\%\f3UP\fP,
\%\f3DOWN\fP,
\%\f3LEFT\fP,
\%\f3RIGHT\fP,
\%\f3ENTER\fP,
etc.
.SH DESCRIPTION
Edgo is a library for text editors providing syntax highlighting and language server protocol (LSP).
It is also providing functionality for text manipulation, search, selection and language queries.
.SH CONFIGURATION
Edgo uses EDGO_CONF and EDGO_LOG environment variables to alter the editor behaviour or to produce
diagnostic logs for debugging. Once the config file path is set you can change themes for the editor
and configure custom LSP servers. Please note however we aim to provide builtin LSP server configurations
for every languages that are supported by the editor. For logging use EDGO_LOG value 1 to enable or 0
to disable logging. All logs are written into system temporary folder.
.SH THEMES
A set of themes are included in the editor and available to be changed in the configuration file.
Some of the themes are darcula, edgo, edgo-new, material-darker, vesper.
.SH LSP SUPPORT
Following lsp features are supported: completion, hover, signature help, definition,
references, rename, method extraction and diagnostic information.
.PP
Install your language server for interaction with your text editor.
.SH SYNTAX HIGHLIGHTING
Following languages are currently supported: bash, c/c++, go, html, css, java, javascript,
typescript, python and rust
.SH BUGS
A comprehensive list of bugs will not be listed in this manpage. See the Github page at
\fBhttps://github.com/vipmax/edgo/issues\fP for a list of known bugs and to report any newly
encountered bugs you may find. We strive to correct bugs as swiftly as possible.
.SH AUTHORS
Edgo was started by Max Petrov and worked on by Marcell Nemes and other contributors.
.SH LICENSE
This project is based on the original work licensed under MIT. See \fBsource/copying.txt\fP
for the original license. Modifications and new code are licensed under GNU GPLv2.
See \fBsource/license.txt\fP for details.
