# Add your source file to the edgo target. All files
# must be listed here individually to keep track
# of the project structure.
target_sources(edgo PRIVATE config.cpp)
target_sources(edgo PRIVATE config.h)
target_sources(edgo PRIVATE selection.cpp)
target_sources(edgo PRIVATE selection.h)
target_sources(edgo PRIVATE operations.h)
target_sources(edgo PRIVATE lsp_user_actions.cpp)
target_sources(edgo PRIVATE lsp_model.h)
target_sources(edgo PRIVATE lsp_capabilities.h)
target_sources(edgo PRIVATE lsp_client.cpp)
target_sources(edgo PRIVATE lsp_client.h)
target_sources(edgo PRIVATE utils.cpp)
target_sources(edgo PRIVATE utils.h)
target_sources(edgo PRIVATE editor.h)
target_sources(edgo PRIVATE screen.cpp)
target_sources(edgo PRIVATE screen.h)
target_sources(edgo PRIVATE characters.cpp)
target_sources(edgo PRIVATE cursor.cpp)
target_sources(edgo PRIVATE highlighter.cpp)
target_sources(edgo PRIVATE highlighter.h)
target_sources(edgo PRIVATE clipboard.cpp)
target_sources(edgo PRIVATE sdl2_init.h)
target_sources(edgo PRIVATE features_v01.cpp)

# embedded scm files
target_sources(edgo PRIVATE lang_bash.h)
target_sources(edgo PRIVATE lang_c.h)
target_sources(edgo PRIVATE lang_cpp.h)
target_sources(edgo PRIVATE lang_css.h)
target_sources(edgo PRIVATE lang_go.h)
target_sources(edgo PRIVATE lang_html.h)
target_sources(edgo PRIVATE lang_java.h)
target_sources(edgo PRIVATE lang_javascript.h)
target_sources(edgo PRIVATE lang_python.h)
target_sources(edgo PRIVATE lang_rust.h)

target_sources(edgo PRIVATE langs.h)
target_sources(edgo PRIVATE themes.h)
target_sources(edgo PRIVATE search.cpp)
target_sources(edgo PRIVATE search.h)
target_sources(edgo PRIVATE query.cpp)
target_sources(edgo PRIVATE query.h)
target_sources(edgo PRIVATE io.cpp)
target_sources(edgo PRIVATE keyboard.cpp)

# interface registers
target_sources(edgo PRIVATE intfreg.cpp)
target_sources(edgo PRIVATE lsp.cpp)
